# Generated by Django 3.1.7 on 2021-02-25 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
