# Generated by Django 3.1.7 on 2021-02-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0007_remove_banner_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
